manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: zhiayang
      url-base: https://github.com/zhiayang
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk
      remote: zhiayang
      revision: mikoto_7_1_0
  self:
    path: config
