manifest:
  remotes:
    - name: Genteure
      url-base: https://github.com/Genteure
  projects:
    - name: zmk
      remote: Genteure
      revision: feat/battery-reporting@5248ed5
      import: app/west.yml
  self:
    path: config
